services:
  - type: web
    name: spamsentry
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: NODE_ENV
        value: production
    healthCheckPath: /
    autoDeploy: true 